"dev experience":
  - .github/**/*
  - package.json
  - yarn.lock
  - .editorconfig
  - .eslintignore
  - .eslintrc.js
  - .gitignore
  - .prettierignore
  - .prettierrc
website: src/**/*
blog: blog/**/*
"docs: algorithm": docs/algorithm/**/*
"docs: css": docs/css/**/*
"docs: design patterns": docs/design-patterns/**/*
"docs: html": docs/html/**/*
"docs: javascript": docs/javascript/**/*
"docs: react": docs/react/**/*
"docs: web": docs/web/**/*
