const fs = require('fs');

const dirNames = fs.readdirSync('./docs');

const sidebars = {};

dirNames.forEach(dirName => {
  sidebars[dirName] = [
    {
      type: 'autogenerated',
      dirName,
    },
  ];
});

const html = require('./html');
const css = require('./css');
const http = require('./http');
const typescript = require('./typescript');
const webpack = require('./webpack');

module.exports = {
  ...sidebars,
  html,
  css,
  http,
  typescript,
  webpack,
};
