const fs = require('fs');

const dirNames = fs.readdirSync('./docs');

const sidebars = {};

dirNames.forEach(dirName => {
  sidebars[dirName] = [
    {
      type: 'autogenerated',
      dirName,
    },
  ];
});

const html = require('./html');
const css = require('./css');
const algorithm = require('./algorithm');
const http = require('./http');
const typescript = require('./typescript');
const webpack = require('./webpack');
const python = require('./python');

module.exports = {
  ...sidebars,
  html,
  css,
  algorithm,
  http,
  typescript,
  webpack,
  python,
};
