module.exports = {
  algorithm: [
    {
      type: 'autogenerated',
      dirName: 'algorithm'
    }
  ],
  css: [
    {
      type: 'autogenerated',
      dirName: 'css'
    }
  ],
  'design-patterns': [
    {
      type: 'autogenerated',
      dirName: 'design-patterns'
    }
  ],
  'fe-guidelines': [
    {
      type: 'autogenerated',
      dirName: 'fe-guidelines'
    }
  ],
  html: [
    {
      type: 'autogenerated',
      dirName: 'html'
    }
  ],
  java: [
    {
      type: 'autogenerated',
      dirName: 'java'
    }
  ],
  go: [
    {
      type: 'autogenerated',
      dirName: 'go'
    }
  ],
  javascript: [
    {
      type: 'autogenerated',
      dirName: 'javascript'
    }
  ],
  nodejs: [
    {
      type: 'autogenerated',
      dirName: 'nodejs'
    }
  ],
  python: [
    {
      type: 'autogenerated',
      dirName: 'python'
    }
  ],
  react: [
    {
      type: 'autogenerated',
      dirName: 'react'
    }
  ],
  typescript: [
    {
      type: 'autogenerated',
      dirName: 'typescript'
    }
  ],
  web: [
    {
      type: 'autogenerated',
      dirName: 'web'
    }
  ],
  webpack: [
    {
      type: 'autogenerated',
      dirName: 'webpack'
    }
  ],
  wiki: [
    {
      type: 'autogenerated',
      dirName: 'wiki'
    }
  ]
};
